### ISSUE TITLE
希望能有高分辨率屏幕的支持

### ISSUE THREAD

**Issue by guopan** [xenon2333/QuickViewPic#1]
现在用的4k屏，文本应用了200%的缩放，程序界面中的文字非常小。
程序设置窗口以及其中的文字也很小。

**Comment by xenon2333** [comment]
感谢反馈。
我最早是没有对缩放作限制的，但当时存在一点问题，为图方便我就加上了固定100%缩放。
刚才我试着解除了限制，结果实在是惨不忍睹。整个界面都变形了。
要知道这个程序对于各个窗口控件的定位是绝对定位，也就是说你改变了字体大小，控件位置并不会跟着一起调整。所以这个修改起来比较麻烦，能不能实现都不好说，而且我现在也没有太多精力来改。
至于另外一个多屏支持，原因是类似的，绝对定位的定位标准就是当前主屏幕，如果要改，牵扯的东西太多了。
所以说近期是不会考虑支持你所说的两个情况的，以后说不准。抱歉啦

**Comment by xenon2333** [comment]
自从上次回复之后，我就一直在想怎么做适配。花了两周时间，做了一个beta版本。
下载链接在这：https://tmp.link/f/654658a93a9ba
这个版本直接去掉了以前的吸附设置，现在你可以直接拖动菜单按钮来移动窗口。当检测到窗口位于屏幕边缘时，才会触发鼠标悬浮的事件。
由于是测试版本，还有一些问题没改，就先不往github上传了。希望你先测试一下，然后及时给我反馈，感谢。

**Comment by guopan** [comment]
钛盘那个beta版链接，我打不开。
测试了一下release版，没有问题。
抱歉这么晚才回复^_^
